### ISSUE TITLE
does not work in heroku

### ISSUE THREAD

**Issue by JonaxHS** [EverythingSuckz/TG-FileStreamBot#10]
I install everything as indicated and when testing the bot it does not work it simply does not start I do not know that it is failing

**Comment by Magneto-noob** [comment]
API_HASH=Your API HASH
API_ID=Your API ID
APP_NAME=YOUR APP NAME AS IT
BOT_TOKEN=YOUR BOT TOKEN
BIN_CHANNEL=-100_____
ENV =True
HAS_SSL=True
NO_PORT= True

FILL ALL THIS VERITABLE CORRECTLY.
BOT WILL WORK.

**Comment by Pritam-Patra** [comment]
Iam getting the following exception, How to fix this?

pyrogram.errors.exceptions.bad_request_400.ButtonUrlInvalid: [400 BUTTON_URL_INVALID]: The button url is invalid (caused by "messages.SendMessage")
