### ISSUE TITLE
[question] does this connect directly to telegram servers?

### ISSUE THREAD

**Issue by asdfzxcvbn** [EverythingSuckz/TG-FileStreamBot#101]
this probably doesn't deserve its own issue, so sorry about that. but i have a question, will the client connect directly to telegram servers for downloading the file? i know some other hosters that rely on telegram do. im looking to get a cheap vps dedicated for this, and i want to know if it will need unlimited bandwidth. thanks!

**Comment by EverythingSuckz** [comment]
> this probably doesn't deserve its own issue, so sorry about that. but i have a question, will the client connect directly to telegram servers for downloading the file? i know some other hosters that rely on telegram do. im looking to get a cheap vps dedicated for this, and i want to know if it will need unlimited bandwidth. thanks!

The "client" here you meant the end user or the bot client?

**Comment by asdfzxcvbn** [comment]
the end user who accesses the url. or whoever, really, i just need to know if i would need unlimited bandwidth on a server

**Comment by asdfzxcvbn** [comment]
after a bit of testing, i've seen that it does indeed take up bandwidth on a server. however, after a bit of scrolling through lowendbox, i found a vps that's perfect for running this! $1/month for 1gb of ram, 1 cpu, and unlimited bandwidth. thanks for your help!

**Comment by EverythingSuckz** [comment]
> after a bit of testing, i've seen that it does indeed take up bandwidth on a server. however, after a bit of scrolling through lowendbox, i found a vps that's perfect for running this! $1/month for 1gb of ram, 1 cpu, and unlimited bandwidth. thanks for your help!

For faster replies, I highly advice you to join our [Telegram chat](https://telegram.me/FreeTalksChat) and asking there.

**Comment by asdfzxcvbn** [comment]
> > after a bit of testing, i've seen that it does indeed take up bandwidth on a server. however, after a bit of scrolling through lowendbox, i found a vps that's perfect for running this! $1/month for 1gb of ram, 1 cpu, and unlimited bandwidth. thanks for your help!
> 
> can you share with service you are using?

i can't remember which service this was anymore, i use xentain now
