### ISSUE TITLE
Difference between FQDN and WEB_SERVER_BIND_ADDRESS

### ISSUE THREAD

**Issue by qomhmd** [EverythingSuckz/TG-FileStreamBot#105]
I want to run this repo using docker-compose on a remote server which has a valid IP address and a domain name. What is the difference between FQDN and WEB_SERVER_BIND_ADDRESS?

**Comment by EverythingSuckz** [comment]
`FQDN` is the domain name that you want to connect, it'll be displayed on the URLs generated by the bot. `WEB_SERVER_BIND_ADDRESS`, on the other hand, is the network interface address (IP address) on which a web server listens for incoming requests. For the most case, you only need to care about `FQDN`. Here, if you need to point to a domain url, just add the domain name to the `FQDN` var.

**Comment by qomhmd** [comment]
Thanks. I think forwarded files would be uploaded to the server; but it seems that this is not the case, is it?

**Comment by EverythingSuckz** [comment]
> Thanks. I thought that forwarded files would be uploaded to the server; but it seems that this is not the case, is it?

No, the bot don't save any files in the server, it makes use of Telegram API to directly stream data via the server to the requested client. It basically act as a proxy. This way, the links are instantly generated.
