### ISSUE TITLE
how to speed up while using nginx?

### ISSUE THREAD

**Issue by Sunda001** [EverythingSuckz/TG-FileStreamBot#110]
could u provide for nginx conf to make the speed faster?

**Comment by EverythingSuckz** [comment]
> could u provide for nginx conf to make the speed faster?

Sorry, I don't have it. Also, how will the config make it faster?

**Comment by EverythingSuckz** [comment]
> Caching nginx?

Sorry, I don't know much about those.

**Comment by pdisk** [comment]
did u find any ways?
