### ISSUE TITLE
docker compose up -d does not work

### ISSUE THREAD

**Issue by lukemin** [EverythingSuckz/TG-FileStreamBot#148]
stuck at 
go: downloading github.com/remyoudompheng/bigfft

**Comment by EverythingSuckz** [comment]
I'll look into it.

**Comment by rong6** [comment]
Hey, you're not alone! I've been stuck on the project `github.com/remyoudompheng/bigfft` when I'm using docker, docker-compose, direct build.

**Comment by Hshsh828** [comment]
كس امك ابن الحكبه تريد تاخذ حسابي انته لوتي بس مو الوت مني اب المنيوجه اختج
تنيج ابن الكحبه بطل هاذا سوالفك شكد تصير ابن القندرة امك منيجه بيك يا ابن
الخرة

في الثلاثاء، ١٦ يوليو ٢٠٢٤ ٥:٢٤ م rong6 ***@***.***> كتب:

**Comment by ivangreat** [comment]
same situation

**Comment by EverythingSuckz** [comment]
Hi, @lukemin @rong6 and @ivangreat I just tried to deploy on my server and it was running perfectly fine. Yes, there was some delay when installing `bigfft`, but it was successful.

**Comment by EverythingSuckz** [comment]
I've fixed the issue by updating the Docker Compose config to use the pre-built image from GitHub Container Registry instead of building the image locally. This should resolve the problem where the process gets stuck at downloading `bigfft`.
