### ISSUE TITLE
Cant Download On Heroku!

### ISSUE THREAD

**Issue by elonteam** [EverythingSuckz/TG-FileStreamBot#28]
Cant Download On Heroku!
Can U help Me Config Heroku?
![2022-1-16 14-17-34](https://user-images.githubusercontent.com/91241092/149649651-0a31581d-0002-4042-adae-d0ef10230116.png)

**Comment by elonteam** [comment]
![2022-1-16 14-21-13](https://user-images.githubusercontent.com/91241092/149649691-21eeaa4c-12d5-4395-9cb2-aebab02a97e7.png)

**Comment by EverythingSuckz** [comment]
@elonteam The app won't run in Heroku anymore

**Comment by elonteam** [comment]
and https://vercel.com/

**Comment by EverythingSuckz** [comment]
@elonteam It was never supposed to runned on vercel in the first place.

**Comment by elonteam** [comment]
How to use :D ^^! can u help me 🍡

**Comment by EverythingSuckz** [comment]
@elonteam As I said before, it won't run in Heroku, so the only available way is to deploy locally / in a vps.

**Comment by elonteam** [comment]
@EverythingSuckz  Yeah :D cant i deploy at here https://railway.app/starters?language=python but i dont know config :D, how to work. u can test code on this server

**Comment by EverythingSuckz** [comment]
@elonteam Yeah it works but you can get your account banned if you deploy on railway.app, this repository violates their ToS.

**Comment by elonteam** [comment]
:D IF u live in india, u need help me :V :D :D :D
