### ISSUE TITLE
Sleeping issue 💤

### ISSUE THREAD

**Issue by Clinton-Abraham** [EverythingSuckz/TG-FileStreamBot#3]
Every 30min bot sleeping 😴

**Comment by AbirHasan2005** [comment]
Try GitHub Workflow or any Heroku App Ping Tool.

**Comment by Clinton-Abraham** [comment]
Ok thank u bro..🙂

**Comment by EverythingSuckz** [comment]
Kindly wait for my next update ;)
Until then, try using [Kaffeine](https://kaffeine.herokuapp.com/) or other tools

**Comment by devsdocs** [comment]
Use cron-job.org

**Comment by Clinton-Abraham** [comment]
:( ban

**Comment by AbirHasan2005** [comment]
> :( ban

You can also ping with GitHub Workflow.
