### ISSUE TITLE
socket.error too much ram usage

### ISSUE THREAD

**Issue by adarsh-goel** [EverythingSuckz/TG-FileStreamBot#36]
*code needs bug fixes waiting since ages -_-*

**Comment by Code-X-Mania** [comment]
@EverythingSuckz @eyMarv seems development is dead maybe code is not being updated

**Comment by EverythingSuckz** [comment]
@Code-X-Mania https://github.com/EverythingSuckz/TG-FileStreamBot/blob/main/LICENSE#L587

**Comment by eyMarv** [comment]
> _code needs bug fixes waiting since ages -_-_

Please shut up, ok?

**Comment by StarkGang** [comment]
> _code needs bug fixes waiting since ages -_-_

Ok sir, why don't you help him by updating using your magic code

**Comment by eyMarv** [comment]
@StarkGang Yeah exactly

**Comment by adarsh-goel** [comment]
shut up uh.. it is kinda needed thing that it is kept updated  . u can archive if project is unmaintained

**Comment by eyMarv** [comment]
@adarsh-goel Stop stealing code

**Comment by adarsh-goel** [comment]
i didnt
