### ISSUE TITLE
bot stopped

### ISSUE THREAD

**Issue by lukemin** [EverythingSuckz/TG-FileStreamBot#40]
[24/03/2022 09:53:03][ERROR] => Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
ps.
1. files and videos sent before the occurred error can be downloaded via the generated links
2. sending files and videos sent after the occurred error, the links cannot be generated
3. after sending **/start** order to the tgbot,  there is no any feedback.

**Comment by EverythingSuckz** [comment]
Will look into it, also, have you tried running the bot in python ≥ 3.9

**Comment by lukemin** [comment]
I am using 3.8 now, and I will try to upgrade to 3.9, feedback later.

**Comment by EverythingSuckz** [comment]
> after upgrading to 3.9., the script stopped working completely. Traceback (most recent call last): File "/usr/lib/python3.9/runpy.py", line 188, in _run_module_as_main mod_name, mod_spec, code = _get_module_details(mod_name, _Error) File "/usr/lib/python3.9/runpy.py", line 147, in _get_module_details return _get_module_details(pkg_main_name, error) File "/usr/lib/python3.9/runpy.py", line 111, in _get_module_details **import**(pkg_name) File "/home/ubuntu/TG-FileStreamBot/WebStreamer/**init**.py", line 6, in from .vars import Var File "/home/ubuntu/TG-FileStreamBot/WebStreamer/vars.py", line 5, in from dotenv import load_dotenv ModuleNotFoundError: No module named 'dotenv'

do `python3.9 -m pip install -r requirements.txt`
then run the bot using `python3.9 -m WebStreamer`

**Comment by lukemin** [comment]
problem solved. Thx
