### ISSUE TITLE
multitoken mode does not work

### ISSUE THREAD

**Issue by lukemin** [EverythingSuckz/TG-FileStreamBot#46]
.evn
API_ID=1012*****
API_HASH=ea8e8e41812******************
BOT_TOKEN=5130***4:AAGkmwTdRlcPSX************
MULTI_TOKEN1=52**5***0:AAF9or7yt4****
MULTI_TOKEN2=5130****4:AAGkmwTd******
BIN_CHANNEL=-1001651968922
PORT=8080
FQDN=domain name
HAS_SSL=True
NO_PORT=True

only the main bot with BOT_TOKEN worked. another bots did not

**Comment by DeekshithSH** [comment]
@lukemin Where Your Running

**Comment by DeekshithSH** [comment]
> .evn API_ID=1012***** API_HASH=ea8e8e41812****************** BOT_TOKEN=5130_**4:AAGkmwTdRlcPSX**_********* MULTI_TOKEN1=52**5**_0:AAF9or7yt4_*** MULTI_TOKEN2=5130****4:AAGkmwTd****** BIN_CHANNEL=-1001651968922 PORT=8080 FQDN=domain name HAS_SSL=True NO_PORT=True
> 
> only the main bot with BOT_TOKEN worked. another bots did not

Means MULTI_TOKEN Bot's are Not Responding to Your Messages?

**Comment by lukemin** [comment]
yes， MULTI_TOKEN Bot's are Not Responding to my Messages. I am running this script on my vps

**Comment by DeekshithSH** [comment]
@lukemin Multi Client Bot's are not Coded to Respond to Messages

**Comment by lukemin** [comment]
> @lukemin Multi Client Bot's are not Coded to Respond to Messages

Is there any way to check the Multi Client Bots working or not?

**Comment by DeekshithSH** [comment]
@lukemin You will See When Starting the Bot
Or Visit the Bot URL

**Comment by lukemin** [comment]
@DeekshithSH 
(venv) root@instance-20210817-1303:/home/ubuntu/TG-FileStreamBot# python3 -m WebStreamer

-------------------- Initializing Telegram Bot --------------------
------------------------------ DONE ------------------------------

---------------------- Initializing Clients ----------------------
Starting - Client 1
This will take some time, please wait...
Multi-Client Mode Enabled
------------------------------ DONE ------------------------------
--------------------- Initalizing Web Server ---------------------
------------------------------ DONE ------------------------------

------------------------- Service Started -------------------------
                        bot =>> ***bot
                        server ip =>> 0.0.0.0
------------------------------------------------------------------

When I vist the web, code are shown as bellow:
{"server_status": "running", "uptime": "30s", "telegram_bot": "@ru***_bot", "connected_bots": 2, "loads": {"bot1": 0, "bot2": 0}, "version": 2.2}

Does it mean all the bots working?

When I sent some photos to the main bot, the script crashed, logs as bellow

the files sent to the main bot

**Comment by DeekshithSH** [comment]
@lukemin Ya i think it's a Error a Bug when Sending Photo The Bot Can't find a Name for The File. Wrench may fix it,

All Of Your Multi-Client Working

**Comment by lukemin** [comment]
THX for your great help.

**Comment by EverythingSuckz** [comment]
Only the main bot will be responding to messages, all other bots are just used for the webserver.
