### ISSUE TITLE
`AttributeError: 'media' object has no attribute 'file_name'`

### ISSUE THREAD

**Issue by EverythingSuckz** [EverythingSuckz/TG-FileStreamBot#47]
```
(venv) root@instance-20210817-1303:/home/ubuntu/TG-FileStreamBot# python3 -m WebStreamer

-------------------- Initializing Telegram Bot --------------------
------------------------------ DONE ------------------------------

---------------------- Initializing Clients ----------------------
Starting - Client 1
This will take some time, please wait...
Multi-Client Mode Enabled
------------------------------ DONE ------------------------------
--------------------- Initalizing Web Server ---------------------
------------------------------ DONE ------------------------------

------------------------- Service Started -------------------------
                        bot =>> ***bot
                        server ip =>> 0.0.0.0
------------------------------------------------------------------
```

When I vist the web, code are shown as bellow:
`{"server_status": "running", "uptime": "30s", "telegram_bot": "@ru***_bot", "connected_bots": 2, "loads": {"bot1": 0, "bot2": 0}, "version": 2.2}`

Does it mean all the bots working?

When I sent some photos to the main bot, the script crashed, logs as bellow:

`[07/04/2022 20:18:44][ERROR] => 'Photo' object has no attribute 'file_name'
Traceback (most recent call last):
  File "/home/ubuntu/TG-FileStreamBot/venv/lib/python3.9/site-packages/pyrogram/dispatcher.py", line 222, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/ubuntu/TG-FileStreamBot/WebStreamer/bot/plugins/stream.py", line 31, in media_receive_handler
    stream_link = f"{Var.URL}{log_msg.message_id}/{quote_plus(get_name(m))}?hash={get_hash(log_msg)}"
  File "/home/ubuntu/TG-FileStreamBot/WebStreamer/utils/file_properties.py", line 55, in get_name
    return media.file_name or ""
AttributeError: 'Photo' object has no attribute 'file_name'`

But when I send some videos, it works.

_Originally posted by @lukemin in https://github.com/EverythingSuckz/TG-FileStreamBot/issues/46#issuecomment-1091667969_

**Comment by wiz64** [comment]
This happens when you send a file to the bot and it contains no name/caption.
as the error says, its on line 55 of the file_properties file:
```
return media.file_name or ""
```
here, the return method isn't implemented properly, it gets the error when it tries to read media.file_name
it can be solved easily by changing it to :
```
if media.file_name:
      return media.file_name
    else:
      return ""
```

**Comment by wiz64** [comment]
##62 I have fixed it here, just merge it
