### ISSUE TITLE
Bot Commands are not working and even bot is not supporting files more than 2 GB.

### ISSUE THREAD

**Issue by HimanshuRastogiOfficial** [EverythingSuckz/TG-FileStreamBot#64]

**Comment by eyMarv** [comment]
Yea it's unmaintaned

**Comment by EverythingSuckz** [comment]
The bot works perfectly on python `3.9.x`
tried running on that?

**Comment by HimanshuRastogiOfficial** [comment]
Yeah, I tried the web app is perfectly working + No error showing in logs but still, the bot is not working.

**Comment by DeekshithSH** [comment]
Use python3.9
Everything will work fine except Bot not responding in python 3.10 or above

**Comment by EverythingSuckz** [comment]
Use python =< `3.9.x` and everything will work fine as expected (See 3aa5718)
