### ISSUE TITLE
`TypeError: init() got an unexpected keyword argument 'name'`

### ISSUE THREAD

**Issue by samucamg** [EverythingSuckz/TG-FileStreamBot#65]
I'm using ubuntu 20.04 python 3.8 and when I start the bot for the first time this work fine.
But after stop and start again I got the error.

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/opt/TG-FileStreamBot/WebStreamer/__init__.py", line 7, in <module>
    from WebStreamer.bot.clients import StreamBot
  File "/opt/TG-FileStreamBot/WebStreamer/bot/__init__.py", line 9, in <module>
    StreamBot = Client(
TypeError: __init__() got an unexpected keyword argument 'name'

**Comment by EverythingSuckz** [comment]
This is becasue you are using an older version of `pyrogram`. Please install the latest version by running
```sh
pip3 install -U pyrogram
```

**Comment by white-devil-00** [comment]
same goes for here

![Screenshot (30)](https://user-images.githubusercontent.com/102788535/198865424-86650364-d074-4d88-b8af-63a1a3c940a1.png)

**Comment by EverythingSuckz** [comment]
> same goes for here
> 
> ![Screenshot (30)](https://user-images.githubusercontent.com/102788535/198865424-86650364-d074-4d88-b8af-63a1a3c940a1.png)

Seems like your pyrogram version is still >2.0.0
maybe try `pip install Pyrogram>=2.0.50`

**Comment by DeekshithSH** [comment]
> > same goes for here
> > ![Screenshot (30)](https://user-images.githubusercontent.com/102788535/198865424-86650364-d074-4d88-b8af-63a1a3c940a1.png)
> 
> Seems like your pyrogram version is still <2.0.0 maybe try `pip install Pyrogram>=2.0.50`

He using python 3.6

**Comment by white-devil-00** [comment]
Old version:Linux(Ubuntu 18.04)
Newer version:Linux (Ubuntu 22.04)

solved After changing os version. python newer can't be installed in older version.
updating the version helped me 
![Screenshot (33)](https://user-images.githubusercontent.com/102788535/198868017-2c18889b-7411-4b90-aac2-d7df70100efa.png)
