### ISSUE TITLE
Deploy to koyeb

### ISSUE THREAD

**Issue by kaissimoha** [EverythingSuckz/TG-FileStreamBot#78]
I've successfully deployed it in koyeb , but the problem is that the port 8080 is showing in the url , and I've tried to change the port to 443 but it doesn't work anymore , any idea how to fix it ?
![Capture](https://user-images.githubusercontent.com/62901183/201788116-317b6658-bd32-4ab5-acbf-5b73a97e6d8a.PNG)

**Comment by EverythingSuckz** [comment]
If the url works without PORT, then add an environment variable `NO_PORT` and set the value to `True`

**Comment by kaissimoha** [comment]
Than it's working PERFECT
