### ISSUE TITLE
Error: 420 FLOOD_WAIT

### ISSUE THREAD

**Issue by qiangweihewu** [EverythingSuckz/TG-FileStreamBot#87]
Just updated the codes, and after restarted, it returned the error logs:
[ERROR] ==> Telegram says: [420 FLOOD_WAIT_X] - A wait of 2838 seconds is required (caused by "auth.ImportBotAuthorization")

Is it common for those who have updated it? Is there any way to fix it?
Thanks!

**Comment by EverythingSuckz** [comment]
Have you restarted the bot way too many times? like in a short period of time?
This error is caused when you **try to login too many times in a short period if time**. The only fix is to **wait for 2838 seconds** and make sure that you **don't restart the bot too often** (every minute or so). Also, are you on Docker?

**Comment by qiangweihewu** [comment]
> @qiangweihewu  Have you restarted the bot way too many times, like in a short period of time?
> 
> This error is caused when you **try to login too many times in a short period if time**. The only fix is to **wait for 2838 seconds** and make sure that you **don't restart the bot too often** (every minute or so). Also, are you on Docker?

Thanks! Should be the case you mentioned, and it works now.
