### ISSUE TITLE
Feature Request For Repo To Make Repo More Awesome 

### ISSUE THREAD

**Issue by IbrahimKhan2004** [EverythingSuckz/TG-FileStreamBot#94]
Hello Sir, could you please add an option for the bot to be used by the owner only? Currently, anyone can use the bot, causing abuse and putting a strain on the hosting provider. Also, would it be possible to add features for media streaming in the browser, banning users, and tracking stats? There have been instances of inappropriate 18+ content being uploaded, and there is no current way to ban these users. Finally, could you consider adding an upstream option for automatically updating the bot so that it does not need to be deployed repeatedly? Thank you. ❤️🖤

**Comment by EverythingSuckz** [comment]
Thank you for your request. Regarding using the bot by the owner only, please refer to issue #93 for more information. Concerning the ability to ban users, there is an ongoing discussion about this in issue #70. If you have specific requirements for tracking stats, please open a new issue and provide a detailed description of your needs. As for media streaming in the browser, the bot currently **supports all media that is supported by the browser**. Any further enhancements beyond that are outside the scope of this project. Thank you for your understanding.
