### ISSUE TITLE
How can I access download link that vps bot sends from my Home network?

### ISSUE THREAD

**Issue by erickyun** [EverythingSuckz/TG-FileStreamBot#97]
Hi,

I have ubuntu vps and when I start the bot with docker compose the default WEB_SERVER_BIND_ADDRESS is 0.0.0.0 

My question is How can I access download link that bot send from everywhere? I want to download the link vps bot sends from my Home network?

So when I try to set Ip to my public adress from https://whatismyipaddress.com/
I get 

`
[Errno 99] error while attempting to bind on address ('public ip', 8080): address not available
`

Any help is appreciated please?

**Comment by EverythingSuckz** [comment]
You'll have to set that value in `FQDN` and `WEB_SERVER_BIND_ADDRESS` should be unchanged.
```
FQDN=125.152.1....
```

If the error still persists, this might be because the port was already being used by some other apps.

**Comment by erickyun** [comment]
Yes thank you sir that worked for me.

But now the genareted links are not downloadable I get `site can't be reached` on chrome?
